
# What are NumPy
It is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
## Performance benifits of Numpy over list int.
Numpy uses fixed types.
- Built in int type needs a lot of space in memory, but Numpy uses less space (less bytes) so it is faster in reading from the memory. 
There is no type checking. 
- Numpy using continous memory. The list will be scattered in the memory and these memory blocks are not next to each other, and the list contains the pointers to where the memory is saved. Numpy uses continuos array with in memeory. Single Instruction Multiple Data (SIMD) vector performs calculations in all the manner.
- Numpy uses effective cache utilization, as the memory is in single continuous location. 

- With list we can insert delete append and concatenate 
- with Numpy we can insert delete append concatenate and many more. 
 Consider 
  a = [1,2,3]
  b = [4,5,6]
  a*b = Error 

  But in Numpy 

  a = np.array([1,2,3])
  b = np.array([4,5,6])
  a*b= np.array([4,10,18])

| Note: The Array is a process of memory allocation

## Applications of Numpy
- We can do all sorts of mathematics. 
- Plotting 
- Backend of applications like Pandas, Connect 4 and Digital Photography like store images using numpy. 
- ML applications, ideas of tensors it uses numpy method for array. 


In [9]:
# Basics
import numpy as np
a = np.array([1,2,3], dtype='int16')
print(a)
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[1 2 3]
[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# Get dimension
a.ndim
b.ndim

2

In [10]:
# Get type 
a.dtype

dtype('int16')

In [11]:
#Get size
a.itemsize

2

In [12]:
#Get total size
a.size

3

# Accessing/Changing specific elements, rows, columns, etc

In [13]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
# get a specific element from [row, colums] 
a[1,5] # 1 is th second row , as it starts with 0

13

In [16]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [18]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]


array([2, 4, 6])

In [20]:
# Change something in exising array
a[1,5] = 20
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [25]:
# Change something in exising array
a[:,1] = [1,2]
print(a)

[[ 1  1  1  4  5  6  7]
 [ 8  2  2 11 12 20 14]]


In [31]:
a[1,5] = 20

a[:,6] = [1,2]
print(a)

[[ 1  1  1  1  5  6  1]
 [ 2  2  2  2 12 20  2]]


In [33]:
# *3-d example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
# Get specific element (work outside in)
b[0,1,1]

4

In [36]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Types of Arrays

In [37]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
# All 1s matrix
np.ones((3,3,3), dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [42]:
# Any other number other than 1s and 0s
np.full((2,2), 77)

array([[77, 77],
       [77, 77]])

In [44]:
# Any other number (full_like) - Allows to take a shape that is already build. Here the a is already build with two rows. and adding int 4 into that shapre
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [46]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.38791221, 0.81510142, 0.58198533],
        [0.72274293, 0.22246156, 0.15769642]],

       [[0.92344228, 0.8418952 , 0.91172298],
        [0.21060431, 0.80478143, 0.29502217]],

       [[0.03535156, 0.70003716, 0.08335974],
        [0.24144769, 0.20217094, 0.52221658]],

       [[0.94039485, 0.18590603, 0.90709101],
        [0.90161264, 0.06201971, 0.82405611]]])

In [47]:
# Random Integer values, -4 ids the start value and 8 is the end value
np.random.randint(-4,8, size=(3,3))

array([[ 2, -4,  6],
       [-4,  1,  3],
       [ 4, -1,  4]])

In [48]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
# Repeat an array, here array repeated 3 times.
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [57]:
# An exercise to build a matrix. 
output = np.ones((5,5))
print(output)
z = np.zeros ((3,3))
print(z)

output [1:4,1:4] = z # replace the second row to 5tyh row and second column to 5 column using values of z.
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### be careful in copying arrays !!!

In [58]:
# As the b is copied the location where a is also pointing the result of a changes if b is modified. In order to do that you should make a copy. a.copy
a = np.array([1,2,3])
b = a
b[0] = 100

print(a)

[100   2   3]


In [61]:
# correct method to copy. 
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


## Mathematics

In [62]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [63]:
a + 2

array([3, 4, 5, 6])

In [64]:
a - 2

array([-1,  0,  1,  2])

In [65]:
a * 2

array([2, 4, 6, 8])

In [66]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [67]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [68]:
a ** 2

array([ 1,  4,  9, 16])

In [69]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### more here: https://numpy.org/doc/stable/reference/routines.math.html

### Linear Algebra

In [70]:
# multiply different matrix together.
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [72]:
# Find the determinant
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

###### Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

- Determinant
- Trace
- Singular Vector Decomposition
- Eigenvalues
- Matrix Norm
- Inverse
- Etc...

### Statistics

In [73]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
np.min(stats)


1

In [75]:
np.max(stats)

6

In [76]:
np.max(stats, axis=1)

array([3, 6])

In [77]:
np.sum(stats, axis=0)

array([5, 7, 9])

## Reorganizing Arrays

In [80]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [81]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [82]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

In [85]:
#Load Data from File
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### advanced indexing  
##### boolean masking and advanced indexing


In [86]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])